name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Force update vulnerable dependencies
        run: |
          npm install esbuild@latest --save-dev
          npm audit fix --force
          
      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'fix: update dependencies to fix vulnerabilities'
          title: 'fix: update dependencies to fix vulnerabilities'
          body: 'Automated PR to fix security vulnerabilities in dependencies'
          branch: fix-dependencies
          base: main 